'extends@':
  type: default
  context: blueprints://pages

form:
  validation: loose

  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          type: tab
          title: PLUGIN_ADMIN.CONTENT
          fields:
            header.thumbnail:
              type: pagemediaselect
              label: THEME_BAREBONES.THUMBNAIL
              style: vertical
              preview_images: true
              ordering@: header.title
            content:
              type: markdown
              label: Content
              style: vertical
              validate:
                type: textarea
              ordering@: header.title

        seo:
          type: tab
          title: THEME_BAREBONES.SEO_TAB
          fields:
            header.metadata.description:
              type: text
              label: THEME_BAREBONES.META_DESCRIPTION_LABEL
              help: THEME_BAREBONES.META_DESCRIPTION_HELP
              style: vertical
            header.metadata.ogImage:
              type: filepicker
              label: THEME_BAREBONES.META_IMAGE_LABEL
              help: THEME_BAREBONES.META_IMAGE_HELP
              style: vertical
              folder: '@self'
              preview_images: true
